### ISSUE TITLE
Are there any suggested alternatives for the LED ring / specifications for lighting gels?

### ISSUE THREAD

**Issue by rooksoup** [Pickering-Lab/EnderScope#6]
Hiya,

We have most of the parts to build an EnderScope ourselves and are just missing the cover glass, LED ring and lighting gels. It appears that the LED ring you list is only available through Amazon or that supplier and the lighting gels via AliExpress - are there any suggested equivalents for these that might be more accessible through the annoying constraints of university wholesale suppliers? Has anyone had success with anything a bit different (I imagine it might require some trial and error without the provided Arduino sketch)?

If you have any kind of specs for the LED ring etc. I can have a go at finding something similar and report back :)

**Comment by niamh-deburca** [comment]
Hey,

So for the LED ring, the one we have listed is a cheaper version of the [Adafruit NeoPixel 16 LED ring](https://www.adafruit.com/product/1463). You could swap this out for any LEDs but if you want something that fits in the LED holder it needs to have the following dimensions: 

![image](https://github.com/Pickering-Lab/EnderScope/assets/130670399/b792aff2-63b5-4bb3-94c8-4665c599cea1)

We have also designed an adjustable LED holder. This allows you to hold individual 5mm 2-pin LEDs on adjustable arms and position them around the objective lens. It's a little fiddly to use which is why I didn't have it up on the repository until now but it should be there for you now in case you have some 2-pin LEDs lying around and want to try it.

For the lighting gels we have also tried these [Roscolux filters](https://www.edmundoptics.eu/f/roscolux-color-filter-swatchbook/12186/) which can be bought from Edmund Optics. They work just as well, not expensive and you can get a big swatch book where each filter comes with its own spectral chart. When we are looking to see Nile Red fluorescence, we have found that the Rose pink #342 filter from the swatch book works really well (when you double up two layers of the filter it works especially well).

Hope this helps! Looking forward to seeing another EnderScope in the wild :)

**Comment by rooksoup** [comment]
That's fantastic to know, thank you! Will hopefully report back soon once we get everything together and have a go.
